root: true

parser: 'babel-eslint'
parserOptions:
    sourceType: 'module'

extends:
    - airbnb

env:
    browser: true
    node: true
    mocha: true
    jest: true

globals:
    should: true

rules:
    max-len:
        - error
        - 120
        - 2
        - ignoreUrls: true
          ignoreComments: false
          ignoreRegExpLiterals: true
          ignoreStrings: true
          ignoreTemplateLiterals: true
    no-await-in-loop: 0
    import/no-unresolved: 0
    import/no-dynamic-require: 0
    import/newline-after-import:
        - error
        - count: 2
    import/extensions: 0

    react/jsx-filename-extension: 0

    global-require: 0
    no-underscore-dangle: 0
    no-unused-vars:
        - error
        - args: none
    no-return-assign: 0
    no-confusing-arrow: 0
    no-nested-ternary: 0
    class-methods-use-this: 0

    require-jsdoc:
        - 2
        - require:
              FunctionDeclaration: true
              MethodDefinition: true
              ClassDeclaration: true
              ArrowFunctionExpression: true
              FunctionExpression: true
    valid-jsdoc:
        - 2
        - requireParamDescription: false
          requireParamType: true
          requireReturnDescription: false
          requireReturn: false
          prefer:
              returns: return
